#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/externaldatabase?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    driver-class-name=com.mysql.jdbc.Driver: com.mysql.jdbc.Driver
